# Generated by Django 4.1.3 on 2022-11-25 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
                ('pays', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Maillot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur', models.CharField(max_length=64)),
                ('marque', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=32)),
                ('equipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projet1WEBA.equipe')),
            ],
        ),
    ]
