# Generated by Django 4.1.3 on 2023-03-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet1WEBA', '0002_equipe_couleurs_equipe_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='couleurs',
            field=models.CharField(default='n/a', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipe',
            name='ville',
            field=models.CharField(max_length=64),
        ),
    ]
